from __future__ import annotations

import json
import os
import re
from typing import Any

from pydantic import ValidationError

from core.config_loader import AppConfig
from core.extraction_cache import cache_key_for_text, load_cached_model, store_cached_model
from core.models import BillData, CalcResult, ClientInfo, NarrativeSections
from core.utils import format_currency, format_kwp, format_number, load_local_env


SYSTEM_PROMPT = """
You are writing a client-facing solar/PPA proposal for Aspan Energy.

You will receive final numbers that were already calculated by a deterministic Python engine.

You must use those numbers exactly as provided.
You must not perform arithmetic.
You must not estimate missing values.
You must not change, round differently, reinterpret, or improve the numbers.
You must not invent warranty terms, contract terms, financing terms, O&M responsibilities, or implementation timelines.
Use only the approved facts pack for Aspan-specific claims.
If a fact is not present, write generally or mark it as requiring Aspan confirmation.
Write for a CFO or business owner.
Be concise, professional, and persuasive.
Return strict JSON only.
"""
DEFAULT_ANTHROPIC_MODEL = "claude-sonnet-4-6"
NARRATIVE_CACHE_VERSION = "proposal-narrative-v1"


def _fallback_narrative(
    bill: BillData,
    client: ClientInfo,
    calc: CalcResult,
    facts_pack_text: str,
) -> NarrativeSections:
    facts_available = bool(facts_pack_text.strip())
    scope_sentence = (
        "Aspan's scope should follow the approved facts pack and be confirmed during commercial review."
        if facts_available
        else "Aspan-specific scope details are to be confirmed by Aspan Energy."
    )
    return NarrativeSections(
        executive_summary=(
            f"Aspan Energy proposes a {format_kwp(calc.pv_recommendation.recommended_kwp)} solar "
            f"PPA solution for {client.client_name}. Estimated annual production is "
            f"{format_number(calc.annual_solar_production_kwh)} kWh. Year 1 savings are "
            f"{format_currency(calc.scenario_grid_replacement.annual_savings_year_1, bill.currency)} "
            f"under Grid Replacement and "
            f"{format_currency(calc.scenario_grid_diesel.annual_savings_year_1, bill.currency)} "
            "under Grid + Diesel operation."
        ),
        current_energy_situation=(
            f"The reviewed bill indicates average monthly consumption of "
            f"{format_number(bill.monthly_kwh)} kWh, monthly cost of "
            f"{format_currency(bill.total_cost, bill.currency)}, and a grid tariff of "
            f"{format_currency(bill.tariff_per_kwh, bill.currency, 3)} per kWh."
        ),
        proposed_solar_solution=(
            f"The recommended system size is {format_kwp(calc.pv_recommendation.recommended_kwp)}, "
            f"with {calc.pv_recommendation.binding_constraint} as the binding constraint. "
            f"Estimated daytime consumption is {format_number(calc.annual_daytime_consumption_kwh)} kWh per year."
        ),
        ppa_model_explanation=(
            "Under the PPA model, the client pays for solar energy generated by the project instead of "
            "funding the full system upfront. Final commercial terms are to be confirmed by Aspan Energy."
        ),
        economic_analysis_summary=(
            f"Across the {calc.assumptions.analysis_horizon_years}-year analysis horizon, estimated cumulative "
            f"savings are {format_currency(calc.scenario_grid_replacement.cumulative_savings, bill.currency)} "
            f"for Grid Replacement and "
            f"{format_currency(calc.scenario_grid_diesel.cumulative_savings, bill.currency)} for Grid + Diesel."
        ),
        scope_of_services=scope_sentence,
        implementation_process=(
            "The next phase should confirm site data, validate assumptions, review commercial terms, "
            "and prepare a detailed proposal for approval."
        ),
        next_steps=(
            "Confirm assumptions, validate roof area, confirm tariff and diesel inputs, complete site assessment, "
            "perform commercial review, and proceed to a detailed proposal."
        ),
    )


def _payload_for_prompt(
    bill: BillData,
    client: ClientInfo,
    calc: CalcResult,
    facts_pack_text: str,
    style_reference: str | None,
) -> str:
    payload = {
        "bill": bill.model_dump(mode="json"),
        "client": client.model_dump(mode="json"),
        "calc_result": calc.model_dump(mode="json"),
        "approved_facts_pack": facts_pack_text,
        "style_reference_for_tone_only": style_reference,
        "required_output_schema": NarrativeSections.model_json_schema(),
    }
    return json.dumps(payload, indent=2)


def _numbers_in_text(text: str) -> set[str]:
    return set(re.findall(r"(?<![A-Za-z])\d+(?:[.,]\d+)?%?", text))


def _allowed_numbers(*objects: Any, config: AppConfig) -> set[str]:
    serialized = json.dumps(
        [obj.model_dump(mode="json") if hasattr(obj, "model_dump") else obj for obj in objects],
        default=str,
    )
    raw_values = re.findall(r"-?\d+(?:\.\d+)?", serialized)
    allowed: set[str] = {"1", "2", "50", "100"}
    allowed.add(str(config.analysis_horizon_years))
    for raw in raw_values:
        value = float(raw)
        allowed.add(str(int(round(value))))
        allowed.add(f"{value:.1f}")
        allowed.add(f"{value:.2f}")
        allowed.add(f"{value:.3f}")
        allowed.add(f"{value:,.0f}")
        allowed.add(f"{value:,.1f}")
        allowed.add(f"{value:,.2f}")
    return allowed


def _remove_unauthorized_number_sentences(
    narrative: NarrativeSections,
    allowed: set[str],
) -> NarrativeSections:
    data = narrative.model_dump()
    for key, text in data.items():
        sentences = re.split(r"(?<=[.!?])\s+", text)
        safe_sentences = [
            sentence
            for sentence in sentences
            if not (_numbers_in_text(sentence) - allowed)
        ]
        data[key] = " ".join(safe_sentences) or "Details to be confirmed by Aspan Energy."
    return NarrativeSections.model_validate(data)


def _call_claude_narrative(prompt_payload: str) -> dict[str, Any]:
    load_local_env()
    from anthropic import Anthropic

    client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
    model = os.getenv("ANTHROPIC_TEXT_MODEL", DEFAULT_ANTHROPIC_MODEL)
    message = client.messages.create(
        model=model,
        max_tokens=2200,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": (
                    "Write proposal sections from this payload. Return only JSON matching the schema.\n\n"
                    f"{prompt_payload}"
                ),
            }
        ],
    )
    text = "".join(block.text for block in message.content if getattr(block, "type", None) == "text")
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise json.JSONDecodeError("No JSON object found", text, 0)
    return json.loads(match.group(0))


def generate_narrative(
    bill: BillData,
    client: ClientInfo,
    calc: CalcResult,
    facts_pack_text: str,
    style_reference: str | None,
    config: AppConfig,
) -> NarrativeSections:
    load_local_env()
    if not os.getenv("ANTHROPIC_API_KEY"):
        return _fallback_narrative(bill, client, calc, facts_pack_text)

    payload = _payload_for_prompt(bill, client, calc, facts_pack_text, style_reference)
    model = os.getenv("ANTHROPIC_TEXT_MODEL", DEFAULT_ANTHROPIC_MODEL)
    cache_key = cache_key_for_text(NARRATIVE_CACHE_VERSION, payload, model)
    cached = load_cached_model(cache_key, NarrativeSections)
    if cached is not None:
        return cached
    allowed = _allowed_numbers(bill, client, calc, config=config)
    last_error: Exception | None = None
    try:
        max_attempts = max(1, int(os.getenv("NARRATIVE_MAX_ATTEMPTS", "1")))
    except ValueError:
        max_attempts = 1
    for _attempt in range(max_attempts):
        try:
            generated = NarrativeSections.model_validate(_call_claude_narrative(payload))
            unauthorized = _numbers_in_text(" ".join(generated.model_dump().values())) - allowed
            if unauthorized:
                generated = _remove_unauthorized_number_sentences(generated, allowed)
            store_cached_model(cache_key, generated)
            return generated
        except (ValidationError, json.JSONDecodeError, Exception) as exc:  # noqa: BLE001
            last_error = exc
            payload += f"\n\nPrevious attempt failed validation: {exc}. Return stricter JSON."

    fallback = _fallback_narrative(bill, client, calc, facts_pack_text)
    if last_error:
        fallback = _remove_unauthorized_number_sentences(fallback, allowed)
    store_cached_model(cache_key, fallback)
    return fallback
